export const ROUTES = {
  home: '/',
  auth: {
    login: '/admin/login',
  },
  admin: {
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    courses: '/admin/courses',
    classes: '/admin/classes',
    batches: '/admin/batches',
    graduations: '/admin/graduations',
    schedule: '/admin/schedule',
    assignments: '/admin/assignments',
    certificates: '/admin/certificates',
    analytics: '/admin/analytics',
    messages: '/admin/messages',
    notifications: '/admin/notifications',
    billing: '/admin/billing',
    security: '/admin/security',
    backup: '/admin/backup',
    integration: '/admin/integration',
    mobile: '/admin/mobile',
    monitor: '/admin/monitor',
    storage: '/admin/storage',
    email: '/admin/email',
    support: '/admin/support',
    help: '/admin/help',
    settings: '/admin/settings',
  },
  student: {
    dashboard: '/student/dashboard',
  },
  teacher: {
    login: '/teacher/login',
    dashboard: '/teacher/dashboard',
    modules: '/teacher/modules',
    students: '/teacher/students',
    classes: '/teacher/classes',
    schedule: '/teacher/schedule',
    assignments: '/teacher/assignments',
    exams: '/teacher/exams',
    grades: '/teacher/grades',
    analytics: '/teacher/analytics',
    messages: '/teacher/messages',
    notifications: '/teacher/notifications',
    settings: '/teacher/settings',
    help: '/teacher/help',
  },
} as const;
